package top.aiome.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSms<M extends BaseSms<M>> extends Model<M> implements IBean {

	public void setSmsId(java.lang.String smsId) {
		set("smsId", smsId);
	}

	public java.lang.String getSmsId() {
		return get("smsId");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setValidTime(java.util.Date validTime) {
		set("validTime", validTime);
	}

	public java.util.Date getValidTime() {
		return get("validTime");
	}

}
