package top.aiome.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFeedback<M extends BaseFeedback<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setCreationDate(java.lang.Long creationDate) {
		set("creationDate", creationDate);
	}

	public java.lang.Long getCreationDate() {
		return get("creationDate");
	}

	public void setSuggestion(java.lang.String suggestion) {
		set("suggestion", suggestion);
	}

	public java.lang.String getSuggestion() {
		return get("suggestion");
	}

}
