package top.aiome.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTravel<M extends BaseTravel<M>> extends Model<M> implements IBean {

	public void setTravelId(java.lang.String travelId) {
		set("travelId", travelId);
	}

	public java.lang.String getTravelId() {
		return get("travelId");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setGuiderId(java.lang.String guiderId) {
		set("guiderId", guiderId);
	}

	public java.lang.String getGuiderId() {
		return get("guiderId");
	}

	public void setSchoolId(java.lang.String schoolId) {
		set("schoolId", schoolId);
	}

	public java.lang.String getSchoolId() {
		return get("schoolId");
	}

	public void setTravelTime(java.util.Date travelTime) {
		set("travelTime", travelTime);
	}

	public java.util.Date getTravelTime() {
		return get("travelTime");
	}

	public void setFlag(java.lang.Boolean flag) {
		set("flag", flag);
	}

	public java.lang.Boolean getFlag() {
		return get("flag");
	}

	public void setPathPic(java.lang.String pathPic) {
		set("pathPic", pathPic);
	}

	public java.lang.String getPathPic() {
		return get("pathPic");
	}

}
