package top.aiome.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setProfileImage(java.lang.String profileImage) {
		set("profileImage", profileImage);
	}

	public java.lang.String getProfileImage() {
		return get("profileImage");
	}

	public void setSchoolId(java.lang.String schoolId) {
		set("schoolId", schoolId);
	}

	public java.lang.String getSchoolId() {
		return get("schoolId");
	}

	public void setMajorId(java.lang.String majorId) {
		set("majorId", majorId);
	}

	public java.lang.String getMajorId() {
		return get("majorId");
	}

	public void setEnrollment(java.lang.String enrollment) {
		set("enrollment", enrollment);
	}

	public java.lang.String getEnrollment() {
		return get("enrollment");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setMotto(java.lang.String motto) {
		set("motto", motto);
	}

	public java.lang.String getMotto() {
		return get("motto");
	}

	public void setPoint(java.lang.Integer point) {
		set("point", point);
	}

	public java.lang.Integer getPoint() {
		return get("point");
	}

	public void setConstellation(java.lang.String constellation) {
		set("constellation", constellation);
	}

	public java.lang.String getConstellation() {
		return get("constellation");
	}

	public void setFlag(java.lang.Boolean flag) {
		set("flag", flag);
	}

	public java.lang.Boolean getFlag() {
		return get("flag");
	}

	public void setCreatDate(java.lang.Long creatDate) {
		set("creatDate", creatDate);
	}

	public java.lang.Long getCreatDate() {
		return get("creatDate");
	}

	public void setStars(java.lang.Integer stars) {
		set("stars", stars);
	}

	public java.lang.Integer getStars() {
		return get("stars");
	}

	public void setTravelIdUser(java.lang.String travelIdUser) {
		set("travelIdUser", travelIdUser);
	}

	public java.lang.String getTravelIdUser() {
		return get("travelIdUser");
	}

	public void setTravelIdGuider(java.lang.String travelIdGuider) {
		set("travelIdGuider", travelIdGuider);
	}

	public java.lang.String getTravelIdGuider() {
		return get("travelIdGuider");
	}

}
