package top.aiome.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRemainprize<M extends BaseRemainprize<M>> extends Model<M> implements IBean {

	public void setRemainPrizeId(java.lang.String remainPrizeId) {
		set("remainPrizeId", remainPrizeId);
	}

	public java.lang.String getRemainPrizeId() {
		return get("remainPrizeId");
	}

	public void setPrizeName(java.lang.String prizeName) {
		set("prizeName", prizeName);
	}

	public java.lang.String getPrizeName() {
		return get("prizeName");
	}

	public void setPrizeCount(java.lang.Integer prizeCount) {
		set("prizeCount", prizeCount);
	}

	public java.lang.Integer getPrizeCount() {
		return get("prizeCount");
	}

}
