package top.aiome.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAllocateprize<M extends BaseAllocateprize<M>> extends Model<M> implements IBean {

	public void setAllocatePrizeId(java.lang.String allocatePrizeId) {
		set("allocatePrizeId", allocatePrizeId);
	}

	public java.lang.String getAllocatePrizeId() {
		return get("allocatePrizeId");
	}

	public void setPrizeName(java.lang.String prizeName) {
		set("prizeName", prizeName);
	}

	public java.lang.String getPrizeName() {
		return get("prizeName");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

}
