package top.aiome.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollege<M extends BaseCollege<M>> extends Model<M> implements IBean {

	public void setCoid(java.lang.Integer coid) {
		set("coid", coid);
	}

	public java.lang.Integer getCoid() {
		return get("coid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setProvinceID(java.lang.Integer provinceID) {
		set("provinceID", provinceID);
	}

	public java.lang.Integer getProvinceID() {
		return get("provinceID");
	}

	public void setLantitude(java.lang.Double lantitude) {
		set("lantitude", lantitude);
	}

	public java.lang.Double getLantitude() {
		return get("lantitude");
	}

	public void setLongitude(java.lang.Double longitude) {
		set("longitude", longitude);
	}

	public java.lang.Double getLongitude() {
		return get("longitude");
	}

}
