package top.aiome.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("allocateprize", "allocatePrizeId", Allocateprize.class);
		arp.addMapping("college", "coid", College.class);
		arp.addMapping("college_comment", "commentId", CollegeComment.class);
		arp.addMapping("major", "scid", Major.class);
		arp.addMapping("match", "matchId", Match.class);
		arp.addMapping("province", "pid", Province.class);
		arp.addMapping("remainprize", "remainPrizeId", Remainprize.class);
		arp.addMapping("sms", "smsId", Sms.class);
		arp.addMapping("travel", "trivalId", Travel.class);
		// Composite Primary Key order: stars,userId
		arp.addMapping("user", "stars,userId", User.class);
		arp.addMapping("user_comment", "commentId", UserComment.class);
	}
}

