package top.aiome.common.model;

import top.aiome.common.model.base.BaseAllocateprize;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Allocateprize extends BaseAllocateprize<Allocateprize> {
	public static final Allocateprize dao = new Allocateprize();
}
