package top.aiome.common.model;

import top.aiome.common.model.base.BaseCollege;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class College extends BaseCollege<College> {
	public static final College dao = new College();
}
