package top.aiome.common.model;

import top.aiome.common.model.base.BaseCollegeComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollegeComment extends BaseCollegeComment<CollegeComment> {
	public static final CollegeComment dao = new CollegeComment();
}
