package top.aiome.common.model;

import top.aiome.common.model.base.BaseLoginUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginUser extends BaseLoginUser<LoginUser> {
	public static final LoginUser dao = new LoginUser();
}
