package top.aiome.common.model;

import top.aiome.common.model.base.BaseMajor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Major extends BaseMajor<Major> {
	public static final Major dao = new Major();
}
