package top.aiome.common.model;

import top.aiome.common.model.base.BaseProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Province extends BaseProvince<Province> {
	public static final Province dao = new Province();
}
