package top.aiome.common.model;

import top.aiome.common.model.base.BaseRemainprize;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Remainprize extends BaseRemainprize<Remainprize> {
	public static final Remainprize dao = new Remainprize();
}
