package top.aiome.common.model;

import top.aiome.common.model.base.BaseSms;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sms extends BaseSms<Sms> {
	public static final Sms dao = new Sms();
}
