package top.aiome.common.model;

import top.aiome.common.model.base.BaseTravel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Travel extends BaseTravel<Travel> {
	public static final Travel dao = new Travel();
}
