package top.aiome.common.model;

import top.aiome.common.model.base.BaseUserComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserComment extends BaseUserComment<UserComment> {
	public static final UserComment dao = new UserComment();
}
